version: "3.7"
services:
  app:
    build:
      args:
        user: phu-nguyen
        uid: 1001
      context: ./
      dockerfile: Dockerfile
    image: bobbin
    container_name: bobbin-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bobbin

  db:
    image: mysql:5.7
    container_name: bobbin-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - bobbin

  nginx:
    image: nginx:alpine
    container_name: bobbin-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - bobbin

networks:
  bobbin:
    driver: bridge